//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIMSuite.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Vorname ist erforderlich!")]
        public string Vorname { get; set; }
        [Required(ErrorMessage = "Nachname ist erforderlich!")]
        public string Nachname { get; set; }
        [Required(ErrorMessage = "Username ist erforderlich!")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Email ist erforderlich!")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "Abteilung ist erforderlich!")]
        public string Abteilung { get; set; }
        [Required(ErrorMessage = "Passwort ist erforderlich!")]
        [DataType(DataType.Password)]
        public string Passwort { get; set; }
        /*[Compare("Passwort")]
        [DataType(DataType.Password)]
        public string ConfirmPasswort { get; set; }*/
    }
}
